# Docker-compose file used for creating development database instances

services:
  # Development MQTT server.
  mqtt-broker:
    stdin_open: true
    tty: true
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    user: mosquitto
    volumes:
      - "./docker/mosquitto_config:/mosquitto/config"
      - "./docker/mosquitto_data:/mosquitto/data"
    ports:
      - 1883:1883
      - 9001:9001

  # App database for development
  smarthome-mariadb:
    image: mariadb
    container_name: smarthome-mariadb-dev
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=smarthome
      - MYSQL_USER=smarthome
      - MYSQL_PASSWORD=password
    ports:
      - 3313:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - smarthome-data:/var/lib/mysql

  # Testing database for ci/cd
  testing-smarthome-mariadb:
    image: mariadb
    container_name: smarthome-mariadb-testing
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=testing
      - MARIADB_ROOT_PASSWORD=testing
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=smarthome
      - MYSQL_USER=smarthome
      - MYSQL_PASSWORD=testing
    ports:
      - 3330:3306
    volumes:
      - testing-data:/var/lib/mysql

volumes:
  testing-data:
  smarthome-data:
