consumes:
- application/github.com/smarthome-go/smarthome.v1+json
info:
  description: API documentation for the smarthome server
  title: Smarthome
  version: 1.0.0
paths: {}
produces:
- application/github.com/smarthome-go/smarthome.v1+json
schemes:
- http
swagger: "2.0"
